name: scyther
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  logging: ^1.0.0
  nyxx: any
  nyxx_interactions: any
  toml: any
  http: any
  html: any
  image: any
  deep_pick: any
  time_ago_provider: any
  fnx_rest: ^4.1.1

dev_dependencies:
  lints: any
  test: ^1.24.0
